openapi: "3.0.0"
info:
  title: API overview
  description: >
              Most of the requests require authorization token to be sent in `X-Auth-Token`.
              To start working with API use `POST /users` to create an account and `POST /login` to retrieve an authorization token.
servers:
  - url: http://localhost:9000
    description: Local dev server
tags:
  - name: OAuth
    description: OAuth tokens and applications
  - name: Users
    description: Users management
  - name: Login
    description: Login/logout requests
  - name: Sessions
    description: User sessions request    
components:
  securitySchemes:
    api_key:
      type: apiKey
      description: Authorization Token
      name: X-Auth-Token
      in: header
    oauth2:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: '/authorization'
          tokenUrl: '/token'
          scopes:
            "users:read": "Read any user information"
            "users:edit": "Edit any user information"
            "users:block": "Block/Unblock users"
            "users:create": "Allows create users"
            "permissions:read": "Read global permissions configuration"
            "permissions:edit": "Edit global permissions configuration"
            "internal_web": "Internal web user"
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: Error code
          enum:
            - INTERNAL_SERVER_ERROR
            - USER_NOT_FOUND
            - INVALID_REQUEST
            - APPLICATION_NOT_FOUND
        message:
          type: string
          description: Error message description
        timestamp:
          type: integer
          description: Request timestamp
    RoleCreate:
       type: object
       properties:
          role:
            type: string
            description: user flag
          permissions:
            type: array
            description: user permission array
            items:
              type: string
    RolePermissions:
       type: object
       properties:
          permissions:
            type: array
            description: user permission status
            items:
              type: string
    User:
      type: object
      properties:
        uuid:
          type: string
          description: User unique identifier
        email:
          type: string
          required: false
          description: User email
        phone:
          type: string
          required: false
          description: User phone
        firstName:
          type: string
          required: false
          description: User first name
        lastName:
          type: string
          required: false
          description: User last name
        created:
          type: number
          description: User creation timestamp
    CreateBranch:
      type: object
      required:
       - name
      properties:
        name:
          type: string
          description: Branch Name
        description:
          type: string
        parent:
          type: string
          description: Parent branch Id
